STRICT_MODE = False
NON_DESTRUCTIVE = False
FULL_REFRESH = False
LOG_CACHE_EVENTS = False
USE_CACHE = True


def reset():
    global STRICT_MODE, NON_DESTRUCTIVE, FULL_REFRESH, LOG_CACHE_EVENTS

    STRICT_MODE = False
    NON_DESTRUCTIVE = False
    FULL_REFRESH = False
    LOG_CACHE_EVENTS = False
    USE_CACHE = True
