# Stubs for logbook (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .__version__ import __version__
from .base import (
    CRITICAL as CRITICAL,
    DEBUG as DEBUG,
    ERROR as ERROR,
    Flags as Flags,
    INFO as INFO,
    LogRecord as LogRecord,
    Logger as Logger,
    LoggerGroup as LoggerGroup,
    NOTICE as NOTICE,
    NOTSET as NOTSET,
    NestedSetup as NestedSetup,
    Processor as Processor,
    TRACE as TRACE,
    WARNING as WARNING,
    dispatch_record as dispatch_record,
    get_level_name as get_level_name,
    lookup_level as lookup_level,
    set_datetime_format as set_datetime_format,
)
from .handlers import (
    BrotliCompressionHandler as BrotliCompressionHandler,
    FileHandler as FileHandler,
    FingersCrossedHandler as FingersCrossedHandler,
    GMailHandler as GMailHandler,
    GZIPCompressionHandler as GZIPCompressionHandler,
    GroupHandler as GroupHandler,
    Handler as Handler,
    HashingHandlerMixin as HashingHandlerMixin,
    LimitingHandlerMixin as LimitingHandlerMixin,
    MailHandler as MailHandler,
    MonitoringFileHandler as MonitoringFileHandler,
    NTEventLogHandler as NTEventLogHandler,
    NullHandler as NullHandler,
    RotatingFileHandler as RotatingFileHandler,
    StderrHandler as StderrHandler,
    StreamHandler as StreamHandler,
    StringFormatter as StringFormatter,
    StringFormatterHandlerMixin as StringFormatterHandlerMixin,
    SyslogHandler as SyslogHandler,
    TestHandler as TestHandler,
    TimedRotatingFileHandler as TimedRotatingFileHandler,
    WrapperHandler as WrapperHandler,
    create_syshandler as create_syshandler,
)
from . import compat as compat
from typing import Any

trace: Any
debug: Any
info: Any
warn: Any
warning: Any
notice: Any
error: Any
exception: Any
catch_exceptions: Any
critical: Any
log: Any
default_handler: Any
