# Stubs for logbook._termcolors (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

esc: str
codes: Any
dark_colors: Any
light_colors: Any
x: int

def colorize(color_key: Any, text: Any): ...
