from typing import Any

def get_imported_module_names(): ...
def get_type_origin(t: Any): ...
def type_name(t: Any): ...
def is_special_typing_primitive(t: Any): ...
def is_generic(t: Any): ...
def is_union(t: Any): ...
def is_type_var(t: Any): ...
def is_class_var(t: Any): ...
def is_init_var(t: Any): ...
