ALTER TABLE varchar_widening_002.seed ALTER COLUMN gender TYPE varchar(300);

insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Annie', 'Reynolds', 'areynolds0@nifty.com', 'Amerisource Bergen', '133.30.242.211');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Doris', 'Wood', 'dwood1@skyrock.com', 'Bliss World, LLC', '128.229.89.207');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Andrea', 'Ray', 'aray2@google.co.jp', 'Nelco Laboratories, Inc.', '109.74.153.45');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Frank', 'Morgan', 'fmorgan3@1688.com', 'ALK-Abello, Inc.', '252.211.209.9');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Angela', 'Stanley', 'astanley4@google.fr', 'Gemini Pharmaceuticals, Inc. dba ONDRA Pharmaceuticals', '134.142.194.184');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Ruby', 'Jordan', 'rjordan5@nymag.com', 'Watson Pharma, Inc.', '195.104.60.172');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Kathleen', 'Ryan', 'kryan6@scientificamerican.com', 'SHISEIDO AMERICAS CORPORATION', '209.110.160.192');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Margaret', 'Jacobs', 'mjacobs7@example.com', 'Cardinal Health', '72.36.52.20');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Ernest', 'Brown', 'ebrown8@360.cn', 'West-ward Pharmaceutical Corp', '138.157.61.255');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Elizabeth', 'Phillips', 'ephillips9@japanpost.jp', 'Cellex-C International Inc', '68.46.195.188');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Annie', 'Ellis', 'aellisa@weather.com', 'NATURE REPUBLIC CO., LTD.', '163.128.214.142');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Melissa', 'Olson', 'molsonb@theguardian.com', 'Nelco Laboratories, Inc.', '202.22.153.188');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Timothy', 'Martinez', 'tmartinezc@zimbio.com', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', '45.64.205.47');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Mark', 'Nelson', 'mnelsond@bloomberg.com', '7-Eleven', '91.99.195.160');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Kenneth', 'Hart', 'kharte@berkeley.edu', 'Preferred Pharmaceuticals, Inc.', '207.240.9.102');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Kathryn', 'White', 'kwhitef@csmonitor.com', 'Cantrell Drug Company', '191.178.162.18');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Mary', 'Greene', 'mgreeneg@usnews.com', 'Neutrogena Corporation', '251.226.65.64');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Bruce', 'Peters', 'bpetersh@blogspot.com', 'Sun & Skin Care Research, LLC', '153.227.91.121');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Albert', 'Armstrong', 'aarmstrongi@weather.com', 'Access Business Group LLC', '199.146.159.228');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Beverly', 'Gray', 'bgrayj@spiegel.de', 'Church & Dwight Co., Inc.', '47.3.135.226');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Catherine', 'Taylor', 'ctaylork@walmart.com', 'Matrixx Initiatives, Inc.', '82.24.129.147');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Paula', 'Bradley', 'pbradleyl@edublogs.org', 'Nash-Finch Company', '14.145.193.163');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Terry', 'Campbell', 'tcampbellm@artisteer.com', 'MedVantx, Inc.', '89.181.95.177');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Bruce', 'Stevens', 'bstevensn@ucla.edu', 'Global Pharmaceuticals', '128.81.126.144');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Ruby', 'Bishop', 'rbishopo@telegraph.co.uk', 'General Injectables & Vaccines, Inc.', '191.191.17.173');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Denise', 'Duncan', 'dduncanp@reference.com', 'Bare Escentuals Beauty, Inc.', '150.207.3.163');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Dennis', 'Perkins', 'dperkinsq@1und1.de', 'Altaire Pharmaceuticals Inc.', '21.150.103.133');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Brandon', 'Ray', 'brayr@psu.edu', 'Meijer Distribution Inc', '216.53.187.191');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Ernest', 'Graham', 'egrahams@tinyurl.com', 'BioComp Pharma, Inc.', '49.85.236.162');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Denise', 'Matthews', 'dmatthewst@digg.com', 'Procter & Gamble Manufacturing Co.', '160.4.119.137');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Randy', 'Alexander', 'ralexanderu@goo.gl', 'Reckitt Benckiser Pharmaceuticals Inc', '211.72.176.12');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Aaron', 'Jackson', 'ajacksonv@gizmodo.com', 'Molton Brown LTD (UK)', '226.178.48.73');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Wanda', 'Turner', 'wturnerw@reverbnation.com', 'American Health Packaging', '43.22.122.56');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Stephen', 'Ferguson', 'sfergusonx@kickstarter.com', 'Amneal Pharmaceuticals of New York, LLC', '110.211.112.233');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Jane', 'Bradley', 'jbradleyy@usgs.gov', 'Kroger Company', '186.153.255.125');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Phillip', 'Wood', 'pwoodz@about.com', 'Unit Dose Services', '112.65.6.93');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Jeffrey', 'Howell', 'jhowell10@symantec.com', 'Midlothian Laboratories', '232.92.208.248');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Howard', 'Harvey', 'hharvey11@nhs.uk', 'Novartis Pharmaceuticals Corporation', '50.212.26.218');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Benjamin', 'Johnston', 'bjohnston12@diigo.com', 'Nelco Laboratories, Inc.', '131.109.13.9');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Ernest', 'Burke', 'eburke13@toplist.cz', 'Apotex Corp.', '151.176.178.175');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Joe', 'Wright', 'jwright14@mapy.cz', 'MULTALER & CIE S.A.', '233.55.33.63');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Ronald', 'Griffin', 'rgriffin15@topsy.com', 'Gavis Pharmaceuticals, LLC', '174.233.67.86');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Susan', 'Oliver', 'soliver16@goo.gl', 'Bath & Body Works, Inc.', '104.171.43.12');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Karen', 'Cox', 'kcox17@hp.com', 'Home Sweet Homeopathics', '225.51.182.192');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Antonio', 'Larson', 'alarson18@gov.uk', 'Eight and Company', '243.118.98.188');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Brandon', 'Cook', 'bcook19@mozilla.com', 'Chain Drug Consortium, LLC', '38.64.44.255');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Gary', 'Gray', 'ggray1a@alexa.com', 'Lil'' Drug Store Products, Inc', '43.34.161.60');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Doris', 'Harrison', 'dharrison1b@wiley.com', 'Dispensing Solutions, Inc.', '153.66.74.140');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Clarence', 'Perry', 'cperry1c@issuu.com', 'Nelco Laboratories, Inc.', '14.72.110.59');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Emily', 'George', 'egeorge1d@blogtalkradio.com', 'State of Florida DOH Central Pharmacy', '148.35.114.224');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Dennis', 'Larson', 'dlarson1e@trellian.com', 'G&W Laboratories, Inc.', '134.158.117.11');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Ashley', 'Peters', 'apeters1f@de.vu', 'Mylan Pharmaceuticals Inc.', '50.193.252.146');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Douglas', 'Andrews', 'dandrews1g@mac.com', 'Jubilant HollisterStier LLC', '159.134.237.86');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Craig', 'Dunn', 'cdunn1h@cornell.edu', 'Antigen Laboratories, Inc.', '227.11.100.112');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Heather', 'Black', 'hblack1i@harvard.edu', 'Hospira, Inc.', '61.9.121.22');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Shirley', 'Ruiz', 'sruiz1j@tmall.com', 'Hankuk Bowonbio Co., Ltd', '171.144.250.254');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Carl', 'Martinez', 'cmartinez1k@geocities.jp', 'ALK-Abello, Inc.', '128.216.69.116');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Stephen', 'Anderson', 'sanderson1l@odnoklassniki.ru', 'Cardinal Health', '145.154.63.186');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Diana', 'Payne', 'dpayne1m@ftc.gov', 'Pharmaceutical Associates, Inc.', '98.9.155.136');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Judy', 'Gonzalez', 'jgonzalez1n@walmart.com', 'SHISEIDO CO., LTD.', '73.96.109.149');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Steve', 'Cole', 'scole1o@flickr.com', 'Walgreen Company', '251.244.20.117');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Johnny', 'Ellis', 'jellis1p@time.com', 'Jubilant HollisterStier LLC', '188.153.76.182');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Andrea', 'Hamilton', 'ahamilton1q@dailymail.co.uk', 'ALK-Abello, Inc.', '229.58.149.141');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Sean', 'Kennedy', 'skennedy1r@nifty.com', 'Newton Laboratories, Inc.', '227.105.251.134');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Sara', 'Grant', 'sgrant1s@flickr.com', 'Rubbermaid Commercial Products LLC', '96.211.162.73');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Joan', 'Bennett', 'jbennett1t@forbes.com', 'Nelco Laboratories, Inc.', '143.27.240.163');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Judith', 'Daniels', 'jdaniels1u@theguardian.com', 'Newton Laboratories, Inc.', '164.99.249.153');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Irene', 'Bennett', 'ibennett1v@comsenz.com', 'Cellab Co., Ltd.', '112.104.12.122');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Katherine', 'Perez', 'kperez1w@phpbb.com', 'Temple Industrial Welding Supply Co', '211.31.214.131');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Jean', 'Kim', 'jkim1x@umich.edu', 'Bryant Ranch Prepack', '245.252.150.110');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Walter', 'Hernandez', 'whernandez1y@nbcnews.com', 'Virtus Pharmaceuticals LLC', '200.201.83.21');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Larry', 'Scott', 'lscott1z@quantcast.com', 'BIOKEY INC.', '122.141.109.98');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Gerald', 'Palmer', 'gpalmer20@usgs.gov', 'JAFRA COSMETICS INTERNATIONAL', '60.173.159.145');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Harry', 'Andrews', 'handrews21@alexa.com', 'NCS HealthCare of KY, Inc dba Vangard Labs', '210.64.37.91');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Jerry', 'Morrison', 'jmorrison22@drupal.org', 'Teva Pharmaceuticals USA Inc', '83.190.174.61');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Irene', 'Diaz', 'idiaz23@joomla.org', 'Dolgencorp, LLC', '214.16.44.235');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Brenda', 'Hansen', 'bhansen24@wisc.edu', 'REMEDYREPACK INC.', '167.231.200.232');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Carlos', 'Williamson', 'cwilliamson25@w3.org', 'Kroger Company', '251.202.210.204');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('David', 'Fuller', 'dfuller26@canalblog.com', 'Supervalu Inc', '175.125.205.131');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Norma', 'Bishop', 'nbishop27@jugem.jp', 'Mylan Institutional Inc.', '208.162.25.149');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Brenda', 'Daniels', 'bdaniels28@mediafire.com', 'Space Brands Limited', '92.235.250.138');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Kathy', 'Reed', 'kreed29@prweb.com', 'Rugby Laboratories Inc.', '182.114.174.63');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Anthony', 'Long', 'along2a@dropbox.com', 'Fresenius Kabi USA, LLC', '160.146.121.173');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Craig', 'Palmer', 'cpalmer2b@desdev.cn', 'Bio-Pharm, Inc.', '135.77.134.24');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Rachel', 'Banks', 'rbanks2c@devhub.com', 'Sam''s West Inc', '35.72.5.193');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Kenneth', 'Peters', 'kpeters2d@ocn.ne.jp', 'International Labs, Inc.', '11.38.191.65');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Susan', 'Clark', 'sclark2e@ed.gov', 'Shionogi Inc.', '19.243.67.80');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Walter', 'Sullivan', 'wsullivan2f@vinaora.com', 'STAT Rx USA LLC', '154.137.170.227');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Kathleen', 'Wood', 'kwood2g@salon.com', 'Freds Inc', '155.54.131.149');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Phyllis', 'Henderson', 'phenderson2h@walmart.com', 'REMEDYREPACK INC.', '146.65.150.251');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Cheryl', 'Wells', 'cwells2i@gov.uk', 'Rebel Distributors Corp', '69.127.148.31');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Rose', 'Bradley', 'rbradley2j@un.org', 'Hi-Tech Pharmacal Co., Inc.', '150.101.165.102');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Aaron', 'Moreno', 'amoreno2k@tinypic.com', 'Pharmacia and Upjohn Company', '50.27.226.40');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Amy', 'Campbell', 'acampbell2l@auda.org.au', 'Chi Research, Inc.', '242.64.63.241');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Rebecca', 'Butler', 'rbutler2m@godaddy.com', 'Cardinal Health', '40.55.159.66');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Justin', 'Rodriguez', 'jrodriguez2n@meetup.com', 'Hikma Pharmaceutical', '118.9.132.156');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Donald', 'Nelson', 'dnelson2o@narod.ru', 'Nature''s Way Products, Inc.', '165.174.28.134');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Edward', 'Lawson', 'elawson2p@addtoany.com', 'Apotheca Company', '135.17.238.170');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Paul', 'Bell', 'pbell2q@simplemachines.org', 'Washington Homeopathic Products', '235.149.137.62');
insert into varchar_widening_002.seed (first_name, last_name, email, gender, ip_address) values ('Mark', 'Rose', 'mrose2r@google.pl', 'AMERICAN SALES COMPANY', '164.108.170.187');
