# Stubs for jsonrpc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .dispatcher import Dispatcher as Dispatcher
from .manager import JSONRPCResponseManager as JSONRPCResponseManager
from typing import Any

version: Any
__project__ = __name__
PROJECT = __name__
dispatcher: Any
