# Stubs for jsonrpc.jsonrpc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc
from .jsonrpc1 import JSONRPC10Response
from .jsonrpc2 import JSONRPC20Response
from .utils import JSONSerializable
from typing import Any, Union


class JSONRPCRequest(JSONSerializable, metaclass=abc.ABCMeta):
    @classmethod
    def from_json(cls, json_str: Any) -> Union[JSONRPC10Response, JSONRPC20Response]: ...
    @classmethod
    def from_data(cls, data: Any) -> Union[JSONRPC10Response, JSONRPC20Response]: ...
