# Stubs for jsonrpc.manager (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .exceptions import JSONRPCDispatchException, JSONRPCInvalidParams, JSONRPCInvalidRequest, JSONRPCInvalidRequestException, JSONRPCMethodNotFound, JSONRPCParseError, JSONRPCServerError
from .jsonrpc import JSONRPCRequest
from .jsonrpc1 import JSONRPC10Response
from .jsonrpc2 import JSONRPC20BatchRequest, JSONRPC20BatchResponse, JSONRPC20Response
from .utils import is_invalid_params
from typing import Any, List

logger: Any

class JSONRPCResponseManager:
    RESPONSE_CLASS_MAP: Any = ...
    @classmethod
    def handle(cls, request_str: Any, dispatcher: Any): ...
    @classmethod
    def handle_request(cls, request: Any, dispatcher: Any): ...
    @classmethod
    def _get_responses(cls, requests: List[Any], dispatcher: Any): ...
