STRICT_MODE = False
NON_DESTRUCTIVE = False
FULL_REFRESH = False
USE_CACHE = True
WARN_ERROR = False
WRAP_MODELS_IN_TAGS = False


def reset():
    global STRICT_MODE, NON_DESTRUCTIVE, FULL_REFRESH, USE_CACHE, WARN_ERROR, \
        WRAP_MODELS_IN_TAGS

    STRICT_MODE = False
    NON_DESTRUCTIVE = False
    FULL_REFRESH = False
    USE_CACHE = True
    WARN_ERROR = False
    WRAP_MODELS_IN_TAGS = False
