# Stubs for jsonrpc.tests.test_backend_django.settings (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SECRET_KEY: str
ROOT_URLCONF: str
ALLOWED_HOSTS: Any
DATABASE_ENGINE: str
DATABASES: Any
JSONRPC_MAP_VIEW_ENABLED: bool
