# Stubs for jsonrpc.tests.test_bug29 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest2 as unittest
from ..manager import JSONRPCResponseManager
from typing import Any

def isjsonequal(json1: Any, json2: Any): ...

class TestJSONRPCExamples(unittest.TestCase):
    dispatcher: Any = ...
    def setUp(self) -> None: ...
    def test_none_as_result(self) -> None: ...
