# Stubs for jsonrpc.tests.test_base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest2 as unittest
from ..base import JSONRPCBaseRequest, JSONRPCBaseResponse

class TestJSONRPCBaseRequest(unittest.TestCase):
    def test_data(self) -> None: ...

class TestJSONRPCBaseResponse(unittest.TestCase):
    def test_data(self) -> None: ...
