# Stubs for jsonrpc.tests.test_pep3107 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest2 as unittest
from ..manager import JSONRPCResponseManager

class TestJSONRPCResponseManager(unittest.TestCase):
    def test_typeerror_with_annotations(self) -> None: ...
